// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYzFU65hAIdlT--gYuSyhgu_DVLPYXWk',
    appId: '1:326685101902:web:0981b71bed72a8c9c9d81f',
    messagingSenderId: '326685101902',
    projectId: 'educonnect-dulaty',
    authDomain: 'educonnect-dulaty.firebaseapp.com',
    databaseURL: 'https://educonnect-dulaty-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'educonnect-dulaty.firebasestorage.app',
    measurementId: 'G-TYWPPFBXJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EMMpgkJD_qKuLySV2MzPdplTKcUKk9w',
    appId: '1:326685101902:android:0eb19d0947066a56c9d81f',
    messagingSenderId: '326685101902',
    projectId: 'educonnect-dulaty',
    storageBucket: 'educonnect-dulaty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrW7Bq1M4csEbw4ohWA70_vE3V2uqagT8',
    appId: '1:326685101902:ios:9b4bd021a57eca17c9d81f',
    messagingSenderId: '326685101902',
    projectId: 'educonnect-dulaty',
    storageBucket: 'educonnect-dulaty.firebasestorage.app',
    iosBundleId: 'com.example.educontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrW7Bq1M4csEbw4ohWA70_vE3V2uqagT8',
    appId: '1:326685101902:ios:9b4bd021a57eca17c9d81f',
    messagingSenderId: '326685101902',
    projectId: 'educonnect-dulaty',
    storageBucket: 'educonnect-dulaty.firebasestorage.app',
    iosBundleId: 'com.example.educontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJYzFU65hAIdlT--gYuSyhgu_DVLPYXWk',
    appId: '1:326685101902:web:050291cae1f8865ac9d81f',
    messagingSenderId: '326685101902',
    projectId: 'educonnect-dulaty',
    authDomain: 'educonnect-dulaty.firebaseapp.com',
    storageBucket: 'educonnect-dulaty.firebasestorage.app',
    measurementId: 'G-D83P17Y9LR',
  );
}